Repository Project-HAMi/ascend-device-plugin, pull requests merged in 2025-09, with the labels that each got.

#25 sync config with hami-scheduler
  config.yaml
Labels: lgtm, size/XS, dco-signoff: yes

#31 fix: fix lint action
  .github/workflows/dev.yml
  .golangci.yml
Labels: lgtm, dco-signoff: yes, size/S

#32 fix: fix go.yaml
  .github/workflows/go.yml
Labels: size/XS, dco-signoff: yes

#33 Update CI to be able to compile and update version
  .github/workflows/dev.yml
  OWNERS
  ascend-device-plugin-2.4.1.yaml
  ascend-device-plugin.yaml
Labels: dco-signoff: yes, size/L
